// Code generated by mockery v2.14.0. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockUtil is an autogenerated mock type for the Util type
type MockUtil[V getId] struct {
	mock.Mock
}

// Delete provides a mock function with given fields: k
func (_m *MockUtil[V]) Delete(k string) bool {
	ret := _m.Called(k)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(k)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: k
func (_m *MockUtil[V]) Get(k string) (V, bool) {
	ret := _m.Called(k)

	var r0 V
	if rf, ok := ret.Get(0).(func(string) V); ok {
		r0 = rf(k)
	} else {
		r0 = ret.Get(0).(V)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(k)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Put provides a mock function with given fields: v
func (_m *MockUtil[V]) Put(v V) {
	_m.Called(v)
}

// inspect provides a mock function with given fields:
func (_m *MockUtil[V]) inspect() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUtil creates a new instance of MockUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUtil[V getId](t mockConstructorTestingTNewMockUtil) *MockUtil[V] {
	mock := &MockUtil[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
