// Code generated by mockery v2.14.0. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// mockGetId is an autogenerated mock type for the getId type
type mockGetId struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *mockGetId) GetId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTnewMockGetId interface {
	mock.TestingT
	Cleanup(func())
}

// newMockGetId creates a new instance of mockGetId. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockGetId(t mockConstructorTestingTnewMockGetId) *mockGetId {
	mock := &mockGetId{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
