// Code generated by mockery v2.14.0. DO NOT EDIT.

package passwordutil

import mock "github.com/stretchr/testify/mock"

// MockPasswordUtil is an autogenerated mock type for the PasswordUtil type
type MockPasswordUtil struct {
	mock.Mock
}

// GeneratePassword provides a mock function with given fields:
func (_m *MockPasswordUtil) GeneratePassword() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockPasswordUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPasswordUtil creates a new instance of MockPasswordUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPasswordUtil(t mockConstructorTestingTNewMockPasswordUtil) *MockPasswordUtil {
	mock := &MockPasswordUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
