// Code generated by mockery v2.14.0. DO NOT EDIT.

package pheader

import mock "github.com/stretchr/testify/mock"

// MockPartnerRequest is an autogenerated mock type for the PartnerRequest type
type MockPartnerRequest struct {
	mock.Mock
}

// GetPartnerId provides a mock function with given fields:
func (_m *MockPartnerRequest) GetPartnerId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPartnerSecret provides a mock function with given fields:
func (_m *MockPartnerRequest) GetPartnerSecret() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockPartnerRequest interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPartnerRequest creates a new instance of MockPartnerRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPartnerRequest(t mockConstructorTestingTNewMockPartnerRequest) *MockPartnerRequest {
	mock := &MockPartnerRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
