// Code generated by mockery v2.14.0. DO NOT EDIT.

package pheader

import mock "github.com/stretchr/testify/mock"

// MockErr is an autogenerated mock type for the Err type
type MockErr struct {
	mock.Mock
}

// CodeName provides a mock function with given fields:
func (_m *MockErr) CodeName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Desc provides a mock function with given fields: isDebug
func (_m *MockErr) Desc(isDebug bool) string {
	ret := _m.Called(isDebug)

	var r0 string
	if rf, ok := ret.Get(0).(func(bool) string); ok {
		r0 = rf(isDebug)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockErr interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockErr creates a new instance of MockErr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockErr(t mockConstructorTestingTNewMockErr) *MockErr {
	mock := &MockErr{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
