// Code generated by mockery v2.14.0. DO NOT EDIT.

package pheader

import mock "github.com/stretchr/testify/mock"

// MockPartnerResponse is an autogenerated mock type for the PartnerResponse type
type MockPartnerResponse struct {
	mock.Mock
}

// FormRequestHeader provides a mock function with given fields: reqH, err
func (_m *MockPartnerResponse) FormRequestHeader(reqH Request, err Err) {
	_m.Called(reqH, err)
}

type mockConstructorTestingTNewMockPartnerResponse interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPartnerResponse creates a new instance of MockPartnerResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPartnerResponse(t mockConstructorTestingTNewMockPartnerResponse) *MockPartnerResponse {
	mock := &MockPartnerResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
