// Code generated by mockery v2.9.4. DO NOT EDIT.

package pheader

import mock "github.com/stretchr/testify/mock"

// mockMockConstructorTestingTNewMockPartnerResponse is an autogenerated mock type for the mockConstructorTestingTNewMockPartnerResponse type
type mockMockConstructorTestingTNewMockPartnerResponse struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockMockConstructorTestingTNewMockPartnerResponse) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockMockConstructorTestingTNewMockPartnerResponse) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *mockMockConstructorTestingTNewMockPartnerResponse) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *mockMockConstructorTestingTNewMockPartnerResponse) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
