// Code generated by mockery v2.9.4. DO NOT EDIT.

package rbac

import mock "github.com/stretchr/testify/mock"

// mockMockConstructorTestingTNewMockToken is an autogenerated mock type for the mockConstructorTestingTNewMockToken type
type mockMockConstructorTestingTNewMockToken struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockMockConstructorTestingTNewMockToken) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockMockConstructorTestingTNewMockToken) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *mockMockConstructorTestingTNewMockToken) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *mockMockConstructorTestingTNewMockToken) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
