Environment: "UAT"
AppID: "758.01"
AppAbbr: "LWS"
ReqAppID: "75801"
Server:
  Port: 8084
  GracefulShutdownTime: 15s
  ReadTimeout: 30s
  WriteTimeout: 30s
  IdleTimeout: 120s
  HTTPS:
    Enabled: false
    CertFile: ""
    KeyFile: ""
  CORS:
    MaxAge: 12h
    AllowOrigins: "*" # "*" means no limit, it should be set to frontend domain in prod
    AllowHeaders:
      - Origin
      - Content-Length
      - Content-Type
      - Authorization
    AllowCredentials: true
    AllowMethods: [ GET, POST, PUT, DELETE, HEAD, OPTIONS ]
DebugMode: true
Service:
  Jwt:
    SigningKey: "mysigningkey"
  Session:
    TimeoutSec: 1800
    IsRequireEncryption: false
    WrongPasswordLockLimit: 3
    WrongPasswordLockToStatus: "inactive"
    AllowLoginStatus: "active"
  ForgetPassword:
    SigningKey: "forgetpasswordsigningkey"
    TimeoutSec: 900
  Car:
    PublicUrlTimeHour: 1
  Cache:
    Company:
      CacheTimeInSec: 60
      CacheSize: 100
      MemorizerTimeInMs: 50
  Prefix: "/api/v1/caicc-lws"
  RequestSize: 1048576 # 1MB
  API:
    Web:
      V1:
        Login:
          URL: "/session/login"
          Method: POST
          Enabled: true
        ExtendSession:
          URL: "/session/extend"
          Method: POST
          Enabled: true
        Logout:
          URL: "/session/logout"
          Method: POST
          Enabled: true
        CreateUser:
          URL: "/user/profile"
          Method: POST
          Enabled: true
        EditUser:
          URL: "/user/profile"
          Method: PATCH
          Enabled: true
        GetUser:
          URL: "/user/profile/inquire"
          Method: POST
          Enabled: true
        ChangePassword:
          URL: "/user/change-password"
          Method: POST
          Enabled: true
        ListUser:
          URL: "/user/list"
          Method: POST
          Enabled: true
        DeleteUser:
          URL: "/user/profile"
          Method: DELETE
          Enabled: true
        ForgetPassword:
          URL: "/user/forget-password"
          Method: POST
          Enabled: true
        ResetPassword:
          URL: "/user/reset-password"
          Method: POST
          Enabled: true
        CreateCompany:
          URL: "/company"
          Method: POST
          Enabled: true
        GetCompany:
          URL: "/company/inquire"
          Method: POST
          Enabled: true
        EditCompany:
          URL: "/company"
          Method: PUT
          Enabled: true
        ListCompany:
          URL: "/company/list"
          Method: POST
          Enabled: true
        CreateCar:
          URL: "/car"
          Method: POST
          Enabled: true
        CreateCarFromFile:
          URL: "/car/from-file"
          Method: POST
          Enabled: true
        ListCar:
          URL: "/car/list"
          Method: POST
          Enabled: true
        EditCar:
          URL: "/car"
          Method: PUT
          Enabled: true
        CountCar:
          URL: "/car/count"
          Method: POST
          Enabled: true
        GetCar:
          URL: "/car/inquire"
          Method: POST
          Enabled: true
        SubmitCar:
          URL: "/car/submit"
          Method: POST
          Enabled: true
        CancelCar:
          URL: "/car/cancel"
          Method: POST
          Enabled: true
        DisapproveCar:
          URL: "/car/disapprove"
          Method: POST
          Enabled: true
        ApproveCar:
          URL: "/car/approve"
          Method: POST
          Enabled: true
        RevokeCar:
          URL: "/car/revoke"
          Method: POST
          Enabled: true
        UploadImages:
          URL: "/car/images"
          Method: POST
          Enabled: true
        ListCarModel:
          URL: "/dropdown/car-model"
          Method: POST
          Enabled: true
        ListCarDetails:
          URL: "/dropdown/car-details"
          Method: POST
          Enabled: true
        DeleteImages:
          URL: "/car/images/delete"
          Method: POST
          Enabled: true
Mongo:
  DialInfo:
    Addrs:
      - localhost:27017
    URI: ""
    Timeout: 5s
    Database: "car_ai_core"
    ReplicaSetName: ""
    Source: admin
    Username: ""
    Password: ""
    WriteRetry: false
  TLS:
    Enabled: false
    CertPath: ""
Email:
  Address: "email-smtp.us-east-1.amazonaws.com:587"
  Auth:
    Username: "AKIARFMPIYQ3ZTREYWXZ"
    Password: "BKuwyl3wHF33LghiLxa0Tm2jALl3NLdVhPXeCmySlevb"
    Host: "email-smtp.us-east-1.amazonaws.com"
  Sender: "noreply@smartweb-uat.kasikornbank.com"
  ConnectionPoolSize: 4
  SendTimeout: 20
  RetryAttempts: 3
  RetryTimeout: 3
  Url: "https://smartweb-uat.kasikornbank.com/carlabel/web"
HttpTransport:
  MaxIdleConns: 500
  MaxIdleConnsPerHost: 500
  IdleConnTimeout: 20s
  TlsHandshakeTimeout: 20s
  ResponseHeaderTimeout: 20s
  ExpectContinueTimeout: 20s
CarLogId: "car_approve_log_123456"
MasterFiles:
  Car:
    Path: "./configs/master-file/car/"
    FileName:
      Brand: "brand"
      BrandModelSub: "brand-model-sub"
      BrandModelYears: "brand-model-year"
      BrandModelYearSub: "brand-model-year-sub"
      Province: "province"
      VehicleType: "vehicle-type"
      BodyType: "body-type"
      Color: "color"
      Fuel: "fuel"
      EngineBrand: "engine-brand"
      Gear: "gear"
    FileType: ".csv"
S3:
  Region: "ap-southeast-1"
  Bucket: "758.01-car-ai-core-cap-data"
  Acl: ""
  Encryption: ""
  StorageClass: ""
  Credential:
    SecretAccessKey: ""
    AccessKeyId: ""
